name: CI

on:
    pull_request:
    push:
        branches:
            - "master"
        tags:
            - "*"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout LiveSplit
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Fetch history
              run: git fetch --prune --unshallow --no-recurse-submodules

            - name: Checkout head_ref
              if: ${{ github.head_ref != '' }}
              run: git checkout -b ${{ github.head_ref }} || git checkout ${{ github.head_ref }}

            - name: Set up .NET environment
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"

            - name: Publish LiveSplit for Linux
              run: >
                  dotnet publish
                  -v m
                  -c Release
                  -p:DebugType=None
                  -r linux-x64
                  --self-contained false
                  .\LiveSplit.sln

            - name: Publish UpdateManager for Linux
              run: >
                  dotnet publish
                  -v m
                  -c UpdateManagerExe
                  -p:DebugType=None
                  -r linux-x64
                  --self-contained false
                  .\src\UpdateManager\UpdateManager.csproj

            - name: Run tests
              run: >
                  dotnet test
                  -v m
                  -c Release
                  .\LiveSplit.sln

            - name: Upload build as an artifact
              uses: actions/upload-artifact@v4
              with:
                  name: LiveSplit_Build_Linux
                  path: .\artifacts\publish\LiveSplit\release_linux-x64

            - name: Upload UpdateManager as an artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UpdateManager_Linux
                  path: .\artifacts\publish\UpdateManager\release_linux-x64

            - name: Upload build to LiveSplit.github.io
              if: github.repository == 'LiveSplit/LiveSplit' && github.ref == 'refs/heads/master'
              run: |
                  7z a LiveSplitDevBuild_Linux.zip .\artifacts\publish\LiveSplit\release_linux-x64\*
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git clone -q --branch master --single-branch "https://github.com/LiveSplit/LiveSplit.github.io.git"
                  cd LiveSplit.github.io
                  git checkout -q --orphan artifacts
                  git reset
                  mv ../LiveSplitDevBuild_Linux.zip . -force
                  git add LiveSplitDevBuild_Linux.zip
                  git commit -m "Add Linux Development Build"
                  git push -q --force https://action:${{ secrets.DEV_BUILD_UPLOAD }}@github.com/LiveSplit/LiveSplit.github.io.git
